<!DOCTYPE html>
<html>
    <head>
        <?php echo $this->headTitle(); ?>
        <?php echo $this->headMeta(); ?>
        <?php echo $this->headLink(); ?>
        <?php echo $this->headScript(); ?>
       
        <link rel="stylesheet" href="<?php echo BASE_URL ?>/public/style/css/jquery-ui.css" />
        <script type="text/javascript" src="<?php echo BASE_URL . '/public/style/js/jquery-1.7.2.js' ?>"></script>
        <script type="text/javascript" src="<?php echo BASE_URL . '/public/style/js/script.js' ?>"></script>
        <script type="text/javascript" src="<?php echo BASE_URL . '/public/style/js/plugin.js' ?>"></script>
        <script language="javascript" src="<?php echo BASE_URL ?>/public/style/js/jquery-ui.min.js"></script>

    </head>
    <body>
        <h2>This is the first layout</h2>
        <?php echo $this->layout()->content; ?>
    </body>
</html>